nodes:
- input.visual:
    source: 0
- model.yolox:
    model_type: yolox-tiny
    detect: ["bottle", "Person"]
- draw.bbox:
    show_labels: True  
- dabble.fps
- dabble.bbox_to_3d_loc
- custom_nodes.dabble.obj-detection
- custom_nodes.draw.score
- custom_nodes.draw.ThreeD_coords
- draw.legend:
    show: ["fps"]
- output.screen