nodes:
- input.visual:
    source: 0

# - custom_nodes.model.model-door

# - custom_nodes.model.yolov8

- dabble.fps
- dabble.bbox_to_3d_loc
- custom_nodes.dabble.initiate_datapool
- custom_nodes.dabble.obj-detection
- custom_nodes.dabble.object_onscreen_status
- custom_nodes.dabble.obj-navigation-centering
- custom_nodes.dabble.obj-navigation
- custom_nodes.dabble.calculate-area
- custom_nodes.dabble.object_grabbed_by_hand
- custom_nodes.dabble.mission_complete


# - custom_nodes.dabble.debug
# - custom_nodes.draw.score
# - custom_nodes.draw.ThreeD_coords
- draw.legend:
    show: ["fps"]
- output.screen