# Mandatory configs
# Receive bounding boxes and their respective labels as input. Replace with
# other data types as required. List of built-in data types for PeekingDuck can
# be found at https://peekingduck.readthedocs.io/en/stable/glossary.html.
input: ["obj_blocked_by_hand","obj_blocked_by_hand_hist","img"]
# Example:
# Output `obj_attrs` for visualization with `draw.tag` node and `custom_key` for
# use with other custom nodes. Replace as required.
output: ["obj_blocked_by_hand_hist"]

